name: Get Teams Presence Terraform Pipeline
run-name: Get Teams Presence Terraform ${{ inputs.terraform_action }} by ${{ github.actor }}

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  WORKING_DIR: terraform
  ARM_USE_OIDC: true
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  STATE_STG_LOC: eastus2
  TF_VERSION: 1.3.0

jobs: